#!/bin/zsh

# Determine what OS we are running on
OS=$(uname -s)

### ZSH Configuration ###

SCRIPT_DIR="$( dirname $( dirname "$0" ) )"
SOURCE_DIR="$( dirname "$SCRIPT_DIR" )"
PROFILE="$0"

# completion
autoload -U compinit
compinit

# correction
setopt correctall
alias adb='nocorrect adb'
alias bug='nocorrect bug'
alias build='nocorrect build'
alias guard='nocorrect guard'
alias hg='nocorrect hg'
alias tt='nocorrect tt'

# colors
autoload -U colors && colors
for COLOR in RED GREEN YELLOW BLUE MAGENTA CYAN BLACK WHITE; do
    # wrap colors between %{ %} to let the terminal know these codes do not move the cursor
    eval $COLOR='%{$fg_no_bold[${(L)COLOR}]%}'
    eval BOLD_$COLOR='%{$fg_bold[${(L)COLOR}]%}'
done
eval RESET='%{$reset_color%}'

# prompt
autoload -U promptinit
promptinit

# Set the prompt that I like
precmd()
{
    local BRANCH=""
    BRANCH=`git branch --no-color 2>/dev/null | grep \* | sed "s/^\* \(.*\)$/(${YELLOW}\1${BOLD_WHITE}) /"`
    PS1="${BOLD_WHITE}[${GREEN}%n${BOLD_WHITE}@${YELLOW}%m${BOLD_WHITE}] $BRANCH%#${RESET} "
}

RPROMPT="${BOLD_WHITE}[${WHITE}%~${BOLD_WHITE}]${RESET}"

# pushd/cd options
setopt autopushd     # Make cd work like pushd always
setopt pushdminus    # Allow for expanding the directory history on the command line
setopt pushdsilent   # Keeps the cd/pushd command from echoing the old directory each time

### Environment Configuration ###

for INIT in `ls -d1 $SCRIPT_DIR/Profile/init/*`
do
    source "$INIT"
done

if [[ -d "$HOME/bin" ]] then
    export PATH="$PATH:$HOME/bin"
fi

last-backup
[[ -e "$HOME/.launchd.conf" ]] && launchctl < ~/.launchd.conf 2>&1 | grep -v 'Already loaded' # Launch backup script schedule
