#!/bin/zsh

if [[ -e "/usr/local/bin/go" ]] then
    export GOPATH="$SOURCE_DIR/gopkg:$SOURCE_DIR/gopath"
    export PATH="$PATH:${GOPATH//://bin:}/bin"
    alias goplay="go run /usr/local/Cellar/go/1.0.3/misc/goplay/goplay.go"
fi
