#!/bin/zsh

export PATH="$PATH:$SCRIPT_DIR/bin"

if [[ -d "$HOME/.rvm" ]] then
    [[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM function
    export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
fi
