#!/bin/zsh

# Variables global to the init scripts
OS=$(uname -s)

if [[ $OS == 'Darwin' ]]; then
    SCRIPT_DIR=$(dirname $(dirname $(readlink $HOME/.zshrc)))
else
    SCRIPT_DIR=$HOME/Source/environment
fi

SOURCE_DIR=`dirname $SCRIPT_DIR`

# Load more specific initializations
for init in `ls -d1 $SCRIPT_DIR/zsh/init/*`
do
    source $init
done
unset init
